// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateCommandRequest(ctx context.Context, arg CreateCommandRequestParams) (CommandRequest, error)
	CreateSubCommand(ctx context.Context, arg CreateSubCommandParams) (SubCommand, error)
	DeleteCommandRequest(ctx context.Context, id int64) error
	DeleteSubCommand(ctx context.Context, id int64) error
	GetCommandRequest(ctx context.Context, id int64) (CommandRequest, error)
	GetCommandRequestsByType(ctx context.Context, arg GetCommandRequestsByTypeParams) ([]CommandRequest, error)
	GetLastNEntries(ctx context.Context, limit int64) ([]GetLastNEntriesRow, error)
	GetSubCommand(ctx context.Context, id int64) (SubCommand, error)
	GetSubCommandsByStatus(ctx context.Context, arg GetSubCommandsByStatusParams) ([]SubCommand, error)
	GetSubCommandsWithRequest(ctx context.Context, requestID int64) ([]GetSubCommandsWithRequestRow, error)
	ListCommandRequests(ctx context.Context, arg ListCommandRequestsParams) ([]CommandRequest, error)
	ListSubCommands(ctx context.Context, requestID int64) ([]SubCommand, error)
	UpdateCommandRequest(ctx context.Context, arg UpdateCommandRequestParams) (CommandRequest, error)
	UpdateSubCommandOutput(ctx context.Context, arg UpdateSubCommandOutputParams) (SubCommand, error)
	UpdateSubCommandStatus(ctx context.Context, arg UpdateSubCommandStatusParams) (SubCommand, error)
}

var _ Querier = (*Queries)(nil)
